enum ActionTypeKeys {
	SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER',
	TODO_MARK_COMPLETED_REQUEST = 'TODO_MARK_COMPLETED_REQUEST',
	TODO_MARK_COMPLETED_SUCCESS = 'TODO_MARK_COMPLETED_SUCCESS',
	TODO_MARK_COMPLETED_FAILURE = 'TODO_MARK_COMPLETED_FAILURE'
}

export default ActionTypeKeys;